# VacationPy
----

#### Note
* Keep an eye on your API usage. Use https://developers.google.com/maps/reporting/gmp-reporting as reference for how to monitor your usage and billing.

* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [1]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os
import csv
import json
from pprint import pprint



# Import API key
from api_keys import g_key

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [2]:

# File to Load
file_to_load = "../WeatherPy/output_data/cities.csv"


citi=pd.read_csv(file_to_load)
citi

,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
0,Tuktoyaktuk,69.4541,-133.0374,16.12,94,100,10.25,CA,1636808017
1,Mataura,-46.1927,168.8643,46.96,100,100,1.12,NZ,1636808018
2,Gorontalo,0.5412,123.0595,75.83,95,98,3.98,ID,1636807771
3,Calamar,10.2511,-74.9146,78.75,78,99,6.46,CO,1636808021
4,Yellowknife,62.4560,-114.3525,27.41,95,90,12.66,CA,1636808022
...,...,...,...,...,...,...,...,...,...
574,Itoman,26.1247,127.6694,66.97,90,75,14.97,JP,1636808861
575,Sorgun,39.8101,35.1860,55.02,26,49,1.19,TR,1636808862
576,Kieta,-6.2167,155.6333,79.75,78,94,0.43,PG,1636808865
577,Port Hardy,50.6996,-127.4199,44.98,86,100,6.91,CA,1636808866
578,Sisimiut,66.9395,-53.6735,10.78,79,44,10.87,GL,1636808868

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [3]:

# Configure gmaps with API key
gmaps.configure(api_key=g_key)

# Store 'Lat' and 'Lng' into  locations 
locations = citi[["Lat", "Lng"]].astype(float)
locations

Humidity = citi["Humidity"].astype(float)
Humidity

# Create a humidity Heatmap layer
fig = gmaps.figure()

humidity_layer = gmaps.heatmap_layer(locations, weights=Humidity, 
                                 dissipating=False, max_intensity=100,
                                 point_radius = 4)

fig.add_layer(humidity_layer)

fig

Figure(layout=FigureLayout(height='420px'))

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [9]:

# temp_citi=citi(['Wind Speed']<10,,citi['Cloudiness'==0])
# dream_citi

# df.loc[df['B'] >= 64

hotel_df=citi.loc[citi['Max Temp']<80]
hotel_df=hotel_df.loc[hotel_df['Max Temp']>70]
hotel_df=hotel_df.loc[hotel_df['Wind Speed']<10]
hotel_df=hotel_df.loc[hotel_df['Cloudiness']==0]

hotel_df['Hotel Name']=""
hotel_df

                   
# AND citi['Max Temp']>=70

,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date,Hotel Name
48,Bucerías,20.7500,-105.3333,74.98,90,0,3.65,MX,1636808009,
231,Abhā,18.2164,42.5053,76.82,7,0,9.22,SA,1636808361,
285,Pochutla,15.7432,-96.4661,71.42,51,0,4.41,MX,1636808448,
317,San Vicente,-26.6167,-54.1333,75.99,45,0,5.66,AR,1636808493,
401,Nouadhibou,20.9310,-17.0347,70.38,63,0,4.68,MR,1636808615,
538,Chapecó,-27.0964,-52.6183,77.14,48,0,3.22,BR,1636808620,

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [10]:


# Set parameters to search for a hotel
hotel_names=[]
params = {
    "radius": 5000,
    "types": "hotel",
    "key": g_key
}

# Iterate through 
for index, row in hotel_df.iterrows():
    # get lat, lng from df
    lat = row["Lat"]
    lng = row["Lng"]
    params["location"] = f"{lat},{lng}"

    
  # Use the search term: "lodging" and our latitude and longitude.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

  # Make request and get the JSON data from the search. 
    hotels = requests.get(base_url, params=params).json()
# print(json.dumps(hotels,indent=4,sort_keys=True))
    
    hotel_names.append(hotels['results'][1]['name'])
print(hotel_names)
hotel_df['Hotel Name']=hotel_names
hotel_df

['Royal Decameron Complex - Puerto Vallarta', 'Abha Hotel', 'Hotel Posada San Jose', 'Banco Macro Sucursal 13 San Pedro', 'El Medina', 'Golden Hotel']

,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date,Hotel Name
48,Bucerías,20.7500,-105.3333,74.98,90,0,3.65,MX,1636808009,Royal Decameron Complex - Puerto Vallarta
231,Abhā,18.2164,42.5053,76.82,7,0,9.22,SA,1636808361,Abha Hotel
285,Pochutla,15.7432,-96.4661,71.42,51,0,4.41,MX,1636808448,Hotel Posada San Jose
317,San Vicente,-26.6167,-54.1333,75.99,45,0,5.66,AR,1636808493,Banco Macro Sucursal 13 San Pedro
401,Nouadhibou,20.9310,-17.0347,70.38,63,0,4.68,MR,1636808615,El Medina
538,Chapecó,-27.0964,-52.6183,77.14,48,0,3.22,BR,1636808620,Golden Hotel

In [11]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
locations = hotel_df[["Lat", "Lng"]]

In [12]:
# Add marker layer ontop of heat map

marker= gmaps.marker_layer(locations,
                          info_box_content=hotel_info)
fig.add_layer(marker)


fig

Figure(layout=FigureLayout(height='420px'))